# config.toml
[[models]]
base_url = "https://api.deepseek.com/v1"
api_key = "fsPDB596ZBBXUIBTjPfpDTwMfYw2jflsZq7H4BCIFztLR7iYcrXbLXTsDNbwFc+LFSAzkhhqeoN5sZGqdYoT"
provider = "DeepSeek"
model_name = "deepseek-reasoner"
model_type = "completion"
context_size = 64000
